pipeline {
    agent any
    environment {
        MY_ENV_VAR = 'INITIAL'
        MY_VAR = 'INITIAL MY VAR'
    }
    stages {
        stage('Stage 1') {
            steps {
                echo "MY_ENV_VAR = ${MY_ENV_VAR}"
                echo "MY_VAR = ${MY_VAR}"

            }
        }
        stage('Stage 2') {
            steps {
                script {
                    MY_VAR = 'CHANGED VALUE'
                }
            }
        }
        stage('Stage 3') {
            steps {
                echo "MY_VAR = ${MY_VAR}"
            }
        }
    }
}


