pipeline {
    agent any
    stages {
        stage("demo python 2"){
            agent {docker {image "python:2"}}
            steps{
                sh "python -V"
            }
        }
        stage("demo python 3"){
            agent {docker {image "python:3"}}
            steps{
                sh "python -V"
            }
        }
        stage("demo java 8"){
            agent {docker {image "openjdk:8-alpine"}}
            steps{
                sh "java -version"
            }
        }
    }
}
