pipeline{
    agent any 
    stages{
        stage('Developer Build'){
            agent {docker {image 'javacream/maven'}}
            steps{
                sh 'mvn install'
            }
        }
        stage('Build Docker Image'){
            agent {label 'dind'}
            steps{
                sh 'docker build -t javacream/peopleserver:1.0 ./docker'
            }
        }
        stage('Start Application'){
            agent {label 'dind'}
            steps{
                sh 'docker run --rm -p:8080:8080 javacream/peopleserver:1.0'
            }
        }
        stage('Integration Tests'){
            agent {docker {image 'python'}}
            steps{
                sh 'python integration_tests.py'
            }
        }
    }


}
