pipeline{
    agent any 
    stages{
        stage('Developer Build'){
            agent {docker {image 'maven'}}
            steps{
                sh 'mvn install'
                sh 'ls target'
            }
        }
    }


}
