pipeline{
    agent any 
    stages{
        stage('Developer Build'){
            agent {docker {image 'maven'}}
            steps{
                sh 'mvn -f org.javacream.training.rest.people.server/pom.xml install'
                sh 'ls org.javacream.training.rest.people.server/target'
            }
        }
    }


}
