pipeline {
    agent none
    stages {
        stage('Stage 1') {
            agent {label "linux&&java"}
            steps {
                sh 'java -version'
                sh 'uname -a'
            }
        }
        stage('Stage 2') {
            agent {label "linux&&docker"}
            steps {
                sh 'docker --version'
                sh 'uname -a'
            }
        }
    }
}
