pipeline {
    agent none
    stages {
        stage('Stage 1') {
            agent {label "linux&&java"}
            steps {
                echo 'Hello World'
                sh 'uname -a'
            }
        }
        stage('Stage 2') {
            agent {label "linux&&docker"}
            steps {
                sh 'ls -l'
                sh 'uname -a'
            }
        }
        stage('Stage 3') {
            steps {
                echo "Some random message at the end"
            }
        }
    }
}