pipeline {
  agent none

  stages{
    stage('Java Agent') {
      agent {label "java"}
      steps{
        sh 'echo Hello from Java Agent > content.txt'
        sh 'ls'
        stash name: 'Content', includes: 'content.txt'
      }
      post{
        always{
          cleanWs()
        }
      }
    }
    stage('Docker Agent') {
      agent {label "docker"}
      steps{
        sh 'ls'
        unstash name: 'Content'
        sh 'cat content.txt'        
      }
      post{
        always{
          cleanWs()
        }
      }
    }
  }
}
